version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: koeln
    ports:
      - '5432:5432'
  search:
    image: opensearchproject/opensearch:2.9.0
    environment:
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: admin
    ports:
      - '9200:9200'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  api:
    build: ./backend
    command: npm run start:dev
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/koeln
      ES_NODE: http://search:9200
      REDIS_HOST: redis
    volumes:
      - ./backend:/app
    ports:
      - '3001:3001'
    depends_on:
      - db
      - search
      - redis
  web:
    build: ./frontend
    command: npm run dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - api
